CREATE TABLE IF NOT EXISTS Meetings(
    id int AUTO_INCREMENT PRIMARY KEY,
    host VARCHAR(30),
    message VARCHAR(255),
    meetingDate TIMESTAMP,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
)