ALTER TABLE meeting_attendees
ADD COLUMN `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE meeting_attendees
ADD COLUMN `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;